name: Build Packages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    name: Build Android Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: "stable"
          flutter-version: "3.32.0"

      - name: Get dependencies
        run: flutter pub get

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21.0.6
      - name: Install packages
        run: flutter pub get

      - name: build apk
        run: |
          flutter build apk


      - name: Uploading artifact  
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk